BLO-27 Query filtering upgraded
ESD6-blockr/blockr-data-access pull request #12
Opened 2019-05-16 09:40 UTC by Svenmarim

2019-05-16 10:01 UTC, ronaldvandenbroek approved these changes

2019-05-16 10:21 UTC, Juuldamen commented on src/repositories/concrete/mongoTransactionRepository.ts
> +import { Transaction, TransactionType } from "@blockr/blockr-models";
Put this import in alphabetical order

2019-05-16 10:25 UTC, Juuldamen approved these changes

2019-05-16 18:12 UTC, timofudala requested changes

2019-05-16 18:12 UTC, TimoF97 commented on src/exceptions/fieldDoesNotExist.exeception.ts
> +export class FieldDoesNotExist extends Error {
The class name should actually be `FieldDoesNotExistException`.
Please also mind the fact that there is a typo in the file name. It should be `fieldDoesNotExist.exception.ts`, mind the `.exception` part.

2019-05-16 18:12 UTC, TimoF97 commented on src/repositories/concrete/mongoDbQueryBuilder.ts
> +            } catch (err) {
please change `err` to `error`.

2019-05-16 18:12 UTC, TimoF97 commented on src/repositories/concrete/mongoDbQueryBuilder.ts
> +        return finalQuery.length < 1 ? {} : { $and: finalQuery };
I'm nitpicking, but please change `{}` to `{ }`.

2019-05-21 16:08 UTC, timofudala approved these changes

2019-05-22 09:42 UTC, merged