BLO-27 Generified methods for param query filtering
ESD6-blockr/blockr-data-access pull request #9
Opened 2019-05-14 08:40 UTC by Svenmarim

2019-05-14 09:02 UTC, saltz submitted a review, later dismissed

2019-05-14 09:02 UTC, saltz commented on src/repositories/concrete/mongoBlockchainRepository.ts
> +            for (const block of allBlocks) {
This for -> for -> if -> if code block can be simplified the following way:

```ts
for (const query of queries) {
    const field = blocks[0].blockHeader[query[0]];
                
    if (field) {
        throw FilterException("Field in query does not exists");
    }

    filteredBlocks.push.apply(filteredBlocks,
        (blocks.filter((block) => block.blockHeader[query[0]] === query[1])));
    }
}
```

2019-05-14 09:02 UTC, saltz commented on src/repositories/concrete/mongoBlockchainRepository.ts
> +    private paramQueryEqualsToFieldName(queryName: string): boolean {
This can be removed if the example above is implemented.

2019-05-14 09:26 UTC, quintaartsen requested changes

2019-05-14 09:26 UTC, quintaartsen commented on src/repositories/concrete/mongoTransactionRepository.ts
> +                const field = allTransactions[0][query[0]];
move the duplicate code to a separate class `RepositoryOperations` where these methods can live.

2019-05-14 12:46 UTC, saltz commented
The build is still failing @Svenmarim, please fix this before we start our reviews.

2019-05-15 08:38 UTC, quintaartsen approved these changes

2019-05-15 08:52 UTC, roelvdboom approved these changes

2019-05-15 08:53 UTC, merged